### ISSUE TITLE
chore: make all licenses across codebases Apache-2.0

### ISSUE THREAD

**Issue by TillaTheHun0** [hyper63/hyper#203]
Some packages use `MIT`, other packages use `Apache-2.0`. Licensing all adapters and core with the same license would be ideal.

**Comment by twilson63** [comment]
My thoughts

Core should be Apache 2, adapters whatever you all think, but core should apache2

Why? So we care about both copyright and patient with core

Thx

Tom

**Comment by TillaTheHun0** [comment]
Ah, I see. I missed that the distinction was deliberate. In that case, perhaps it's better to keep core licensed as Apache-2.0 and then all the adapters licensed as MIT?

**Comment by twilson63** [comment]
adapters can be licensed as the contributor sees fit from my perspective, I think @hyper should license all adapters we will support as Apache2.

**Comment by TillaTheHun0** [comment]
Makes sense to me 👍 . I can knock that out real quick in the AM

**Comment by TillaTheHun0** [comment]
This will instead be license files in each respective adapter repo based on decision from #231

**Comment by TillaTheHun0** [comment]
All ports, adapters, apps, and core have been updated with the Apache-2.0 license.
