### ISSUE TITLE
feat: allow load on adapter factories to return a Promise

### ISSUE THREAD

**Issue by TillaTheHun0** [hyper63/hyper#242]
I think we should allow `load` to return a `Promise` instead of just data.

The use case is doing asynchronous tasks before instantiating my adapter ie. reading creds from a file, fetching creds from a server, creating tmp files the adapter may use. So `load` would look something like:

```javascript
export default () => ({
  load: async () => {
    const creds = await (await fetch('https://foo.bar')).json()
    return creds
  },
  link: creds => () => () => {
    return createAdapter(creds)
  }
})
```

I could see this, or allowing `link` to return a Promise of an adapter impl. I think either would work.

**Comment by twilson63** [comment]
Sounds good, maybe let's get hyper as is running on Deno first and deployed to a dev env, then make adjustments? Otherwise, we could end up with a mess.
