### ISSUE TITLE
chg(core): Descending param in the data port does not seem to work

### ISSUE THREAD

**Issue by cawilson1** [hyper63/hyper#257]
When trying to implement ddb desc logic for adapter, I couldn't get past zod errors for listDocuments. Perhaps I was using it wrong, but I didn't see how to do it in the docs.

query string = ?descending=true 
I tried a few other variants, such as ?descending=0

hyper response

{
    "issues": [
        {
            "code": "invalid_arguments",
            "argumentsError": {
                "issues": [
                    {
                        "code": "invalid_type",
                        "expected": "boolean",
                        "received": "string",
                        "path": [
                            0,
                            "descending"
                        ],
                        "message": "Expected boolean, received string"
                    }
                ]
            },
            "path": [],
            "message": "Invalid function arguments"
        }
    ]
}

**Comment by twilson63** [comment]
This must be an error in the express/opine API, the API should take the query params and convert them into the proper object value attributes.
