### ISSUE TITLE
bug: inconsistent rules for cache keys when creating cache document

### ISSUE THREAD

**Issue by TillaTheHun0** [hyper63/hyper#318]
The docs [here](https://docs.hyper.io/cache-value-with-key) indicate the following rules for cache keys:

> must begin with lowercase letter (a-z)
must be lowercase letters (a-z)
digits (0-9)
any of these characters _ $ + - 

However, this does not match the rules being enforced in core [here](https://github.com/hyper63/hyper/blob/792558a50a5525e1a28d946b91e8187bdebc815d/packages/core/lib/cache/doc.js#L74)

The result, when using some characters is an error `key is not valid`

Either the docs are incorrect, or the cache key validation is incorrect.

**Comment by twilson63** [comment]
Yep, the correct rules are in the spec, the implementation was a short example early on to show how one could contribute. I will fix.

**Comment by TillaTheHun0** [comment]
Fixed in #319
