### ISSUE TITLE
bug (connect): not publishing to npm - invalid chars in package.json

### ISSUE THREAD

**Issue by twilson63** [hyper63/hyper#336]

**Comment by TillaTheHun0** [comment]
A specific error in this last run:

`error ../../package.json: Name contains illegal characters`

I believe the name can only contain a `/` if it is a scoped package name ie. `@hyper/monorepo`. Perhaps just changing the root to `monorepo` or `hyper-monorepo`?

**Comment by twilson63** [comment]
Sound good, I will incorporate the change with my next PR - thx

**Comment by TillaTheHun0** [comment]
Fixed in bb557441140c87ba21132dac2c491520ecac2eff
