### ISSUE TITLE
bug(connect): error: TypeError: Self-contained binaries don't support module loading

### ISSUE THREAD

**Issue by TillaTheHun0** [hyper63/hyper#340]
Getting this error when trying to use `hyper-connect` in an app compiled with `deno compile`. I believe this is due to how module dependencies are dynamically loaded in `deps.js`, which is not supported in self contained binaries from `deno compile`. 

Workaround: just running the app without `deno compile` get's around the issue, just a bit slower to spin up.

**Comment by TillaTheHun0** [comment]
One approach could be to use the separate entry points to import dependencies, then inject them down, but that could turn into a tangled mess.

The only other approach I can think is a build step. Something like `parcel` or rollup` to rewrite imports inside of `deps.js` depending on a platform.

**Comment by twilson63** [comment]
@TillaTheHun0 can we close this? I think we removed dynamic loading from hyper-connect

**Comment by TillaTheHun0** [comment]
Yes, this can be closed.
