### ISSUE TITLE
hyper-test is non-deterministic

### ISSUE THREAD

**Issue by cawilson1** [hyper63/hyper#402]
This might be to be expected to a certain degree with e2e tests, but could cause tricky CI problems (not to mention developer confusion). The tests should probably be closer to "stateless" if possible. Some suggestions at the bottom.

**The story:** 
I opened up a new gitpod environment after finishing a feature, ran the normal scripts and got a test failure on the first listDocs test, expecting 9 docs and receiving 14.
 ```
test("GET /data/test - get docs with no flags", () =>
    setup()
      .chain(listDocuments)
      .map((r) => (assertEquals(r.ok, true), r))
      .map((r) => (assertEquals(r.docs.length, 9), r))//failed on this line with an actual value of 14
      .chain(tearDown)
      .toPromise());
```
 After checking through the code with no changes, I checked the db and noticed that the 5 documents from the queryDocs tests were in the db. Most likely this was a result of the valid failure of the queryDocs tests never being run (bc the functionality was not implemented yet) causing the tearDown fn never being called for queryDocs.

This could cause nightmare problems for a CI flow dependent on hypertest. If a developer makes a change, pushes, and a test suite fails even once in the CI env on the CI table, and does not run tearDown, all valid subsequent implementations may fail CI tests with no indication why. The developer would have to know to look in the db (assuming they even have access to the db). Also if the person checking CI is not the developer, they wouldn't know where to begin.
 
**Suggestions:** 
1. Run tearDown before running a test suite OR
2. Ensure tearDown is run every time, regardless of success or failure of prior steps.

3. Create a different table for each test suite, so that tests for for one adapter fn do not pollute another adapter fn (My tests said listDocs was failing, but really it was queryDocs that was wrong). Best case it prevents the issue, worst case, it points the developer to the right place to look.

_Notes:_
A side effect of 1 and 2 is that removeDoc would have to be implemented before any single insertion cases (createDoc, getDoc, etc.), and bulkDocs would have to be implemented before any multiple insertion cases (queryDocs, getDocs) pass. This is already the case though. At the very least, this is probably worth noting on the published library package.

Until I finish queryDocs I have to delete all items in the db each time I want to run hyper test.

**Comment by twilson63** [comment]
Great observations, yes the tearDown should run regardless of failure and can be made to run beforehand as well. Also agreed about having a fully implemented API to run e2e tests, don't exactly know how to improve that, except just document it. Open to suggestions.
