### ISSUE TITLE
Core: Keep the outbound _id, id mapping.

### ISSUE THREAD

**Issue by tripott** [hyper63/hyper#413]
Core: Keep the outbound _id mapping.

**Comment by TillaTheHun0** [comment]
No work may be needed for this, since it has been put in place as part of `apricot`. Keeping it for now, in case i'm misunderstanding the work this issue is tracking.

**Comment by TillaTheHun0** [comment]
Satisfied by #424 which removes the inbound mapping, and keeps the outbound mapping.
