### ISSUE TITLE
Design API Sequence Diagram for Storage Upload Limit: HTTP REST

### ISSUE THREAD

**Issue by tripott** [hyper63/hyper#445]
Create prelim API design sequence diagram for upload for HTTP REST.

https://github.com/hyper63/journal/blob/master/design-docs/002-storage-limits.md

**Comment by TillaTheHun0** [comment]
![hyper-cloud-s3](https://user-images.githubusercontent.com/8246360/155602303-a8231560-b2c8-477a-932d-4f2741a2d848.jpeg)
![hyper-s3-sequence](https://user-images.githubusercontent.com/8246360/155602312-28c80f8d-7eb9-4790-b141-99cf630d1fe6.jpeg)
