### ISSUE TITLE
feat: Add verifySignature to hyper-connect

### ISSUE THREAD

**Issue by tripott** [hyper63/hyper#465]
As a dev user
I want to import a `verifySignature` function from `hyper-connect`
so that I can verify the token sent to me by the hyper queue service.

```
import { verifySignature } from 'hyper-connect'
```

I desire a `verifySignature` function that accepts the following arguments:

1. The  `x-hyper-signature`  token value (signature) from the HTTP request sent by hyper queue.
2. The request body (payload) from the HTTP request sent by hyper queue.
3. The shared secret that was configured when the hyper queue service instance was created
4. An optional acceptable time range (TTL).

The function would use the secret, time range (TTL), signature,  request body payload to verify the  'x-hyper-signature' token value (signature) and report back if the signature was ok along with a message and a status code. 

The function could be generic enough to use in different frameworks rather than assuming something like Expressjs middleware. 

```js
const verifySignature = (secret: string, ttl?: string) =>
  (signature: string, payload: JSON) =>
    { ok: boolean, msg?: string, status?: number }
```

## Reference

One example of current `verifySignature` as it exists as ExpressJS middleware. See **[quickstarts-expressjs](https://github.com/hyper63/quickstarts-expressjs)/queue-target/target/verify-sig.js**

```js
// express middleware
import forge from 'node-forge'
const fiveMins = 5 * 60 * 1000
const secret = process.env['WORKER_SECRET']

export default function (req, res, next) {
  const [timepart, sigpart] = req.headers['x-hyper-signature'].split(',')

  const [, time] = timepart.split('t=')
  const [, sig] = sigpart.split('sig=')

  const hmac = forge.hmac.create()
  hmac.start('sha256', secret)
  hmac.update(`${time}.${JSON.stringify(req.body, null, 0)}`)
  const computed = hmac.digest().toHex()

  // payload or time signature was tampered with
  if (computed !== sig) {
    return res.setStatus(401).send('Unauthorized')
  }

  const now = new Date().getTime()
  const dateSent = new Date(time).getTime()
  const diff = now - dateSent

  // timestamp in the future, or not within 5 minutes
  if (diff < 0 || diff > fiveMins) {
    return res.setStatus(422).send('Timestamp not within acceptable range')
  }

  // continue
  next()
}
```

**Comment by TillaTheHun0** [comment]
Done in #466
